name: Lint Git Commits

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Run GitLint
        run: pipx run -- gitlint --commits "${{ github.event.pull_request.base.sha }}..HEAD"
